* 大师写作班这样写出好故事(情节与结构+人物对话+描写与背景)
:PROPERTIES:
:NOTER_DOCUMENT: ../../Downloads/大师写作班这样写出好故事(情节与结构+人物对话+描写与背景).epub
:NOTER_PAGE: (7 . 5515)
:END:

** 开头的承诺，要做到的东西
:PROPERTIES:
:NOTER_PAGE: (7 1657 . 1719)
:END:

``开头永远聚焦于故事里的人物（第四章会详细讨论小说开头）。你的切入点就是主角，你应该让读者尽快与主角产生共鸣——罗宾汉去打猎。''

- 呈现小说中的世界——告诉读者故事的场景设定、时代和相关背景。

- 奠定小说的调性，让读者有所依据。你写的是气势万钧的史诗小说，还是滑稽古怪的闹剧？动作场景连篇还是注重角色变化？步调飞快还是闲散？

- 说服读者继续读到中段。为什么读者要关心你的故事，继续读下去？

- 介绍对手出场。哪些人、事想要阻挡主角？

** 中段的作用
:PROPERTIES:
:NOTER_PAGE: (7 . 2204)
:END:

小说的主要部分便是冲突，由主角和对手之间一系列的攻防战构成。他们打架。

中段还会萌生出支线情节，增添小说的复杂性，并且通常会反映出小说想表达的深层蕴涵。

不同的故事线彼此纵横交错，创造出无法抗拒的宿命感，同时用各种方式带给读者惊喜。除此之外，中段还需要（我会在第五章深入讨论）：

·加深角色之间的关系。

·让观众持续关心故事发展。

·铺陈替故事收尾的最后一战。

** 结尾要回收所有的线索，创造余韵
:PROPERTIES:
:NOTER_PAGE: (7 2298 . 2398)
:END:

#+BEGIN_QUOTE
·把所有的梗收干净。还有没处理完的故事线吗？你一定要把埋好的梗收掉，但不能影响到主线情节，否则就干脆回头把梗删掉。不要小看读者的记忆力。

·创造余韵。最好的结局往往会留给读者小说之外还有戏的感觉。

#+END_QUOTE

** 英雄之旅结果和将它分作三幕式
:PROPERTIES:
:NOTER_PAGE: (7 2563 . 3025)
:END:

#+BEGIN_QUOTE
虽然这套结构有许多不同版本，但通常都依循类似的模式：

·介绍读者认识英雄的世界。

·“出发探险的召唤”或意外事件打乱了英雄的世界。

·英雄可能忽略召唤或意外事件。

·英雄“跨越界线”进入黑暗世界。

·可能出现一名精神导师教导英雄。

·英雄多次遭遇黑暗力量。

·英雄面对内心黑暗的心魔，必须克服心魔才能继续前进。

·一样护身符会协助英雄战斗（例：帕修斯的雅典娜盾牌(1)、亚瑟王的石中剑）。

·最后一战开打。

·英雄回到自己的世界。

为什么这套结构有用？因为它完全符合三幕结构：

第一幕

（1）介绍读者认识英雄的世界。

（2）“出发探险的召唤”或意外事件打乱了英雄的世界。

（3）英雄可能忽略召唤或意外事件。

（4）英雄“跨越界线”进入黑暗世界。

第二幕

（5）可能出现一名精神导师教导英雄。

（6）英雄多次遭遇黑暗力量。

（7）英雄面对并克服内心黑暗的心魔。

（8）一样护身符会协助英雄战斗。

第三幕

（9）最后一战开打。

（10）英雄回到自己的世界。

◎扰乱事件及两扇门

#+END_QUOTE

** 第一幕的开头要发生点什么事情
:PROPERTIES:
:NOTER_PAGE: (7 3417 . 3437)
:END:

``如果事件不快点发生，你的开头就要无聊掉了''

** 扰乱事件的例子
:PROPERTIES:
:NOTER_PAGE: (7 3667 . 3440)
:END:

#+BEGIN_QUOTE
扰乱事件不一定要是严重的威胁，只要打乱主角平静的日常生活就好。美国悬疑小说家迪恩·孔茨（Dean Koontz）的小说通常都以扰乱事件开始，以下是其以笔名理查德·佩基（Richard Paige）出版的《通往十二月的门》（The Door to December）开头第一句：

萝拉一穿好衣服就走到大门口，刚好看到洛杉矶警局的警车停在门前的人行道旁。

这就是扰乱事件，虽然是小事，但还是打乱了她的日常生活。通常警车停在家门口，大家都不会感到太舒服。

#+END_QUOTE

** 扰乱事件是什么和不是什么，与第一扇门的区别
:PROPERTIES:
:NOTER_PAGE: (7 3809 . 3882)
:END:

``第一个扰乱事件能引起读者的兴趣，暗示接下来要讲一个有趣的故事。然而这时还没来到情节的主要段落，因为冲突还没发生，对手和主角还没陷入不可避免的战斗。''

第一个扰乱事件引发读者注意，让主角初步陷入一些麻烦之中，这是他还有回转的余地，可以退出。第一扇门打开，主角跨过之后，就不能回头了。

** 第一扇门和第一个扰乱事件的例子
:PROPERTIES:
:NOTER_PAGE: (7 3911 . 4417)
:END:

#+BEGIN_QUOTE
《教父》（The Godfather）中，年轻的迈克·柯里昂决心走上正道，避免步上父亲的后尘。然而父亲遭到枪击几乎丧命时，迈克的世界瞬间变色。不过迈克还没卷入冲突当中，他大可离开纽约，到别的地方展开新人生。直到主角穿过第一扇门，冲突才会产生，故事才会加速发展。

乔治·卢卡斯的电影《星球大战》以动作场景当作序章。黑武士和手下士兵追踪并抓走莉亚公主，然而被抓之前，公主抢先将R2-D2和C-3PO装进救生舱送走了。这两名机器人降落在塔图因星球上，被贩卖垃圾的爪哇人抓住。

观众接着见到主角卢克·天行者，他在他的原始世界塔图因工作，与叔叔阿姨住在一起。他的叔叔买了这两名机器人，结果才不过五分钟，卢克的世界就被打乱了：莉亚公主传来求救立体投影，寻求欧比王·肯诺比的协助。

卢克终于联系上欧比王，欧比王看了求救信息，并邀请卢克一起帮忙拯救公主。卢克拒绝了他的“召唤”（依照英雄旅程结构的说法），告诉欧比王他无法抛下叔叔、阿姨。

这还不是进入第二幕的门，因为卢克还是可以继续过他平淡的生活。然而等到帝国大军摧毁了卢克的家，杀了他的叔叔、阿姨，卢克便被一把推进了反抗军。他与欧比王离开塔图因，开始了他的冒险旅程。

#+END_QUOTE

** 两扇门的说明
:PROPERTIES:
:NOTER_PAGE: (7 4510 . 4789)
:END:

#+BEGIN_QUOTE
无法折返代表了你想创造的感觉：将主角往前推的力量，一种无可避免的氛围。人类总是安于现状，追求安定。我们笔下的角色也一样，除非发生什么事将主角推进第二幕，否则他只会心满意足地待在第一幕！他只渴望留在自己平凡的世界里。

你必须想办法把他赶出平凡的世界，逼他面对冲突。你需要某样东西把他踢过那扇门，否则他只会赖在家里不走。

一旦穿过门，就可以产生冲突了。第二幕会持续描写主角的奋斗，但故事总得结束，因此第二扇无法折返的门必须将主角快速送往冲击结局。

这两扇门负责把三幕情节串联起来，就像联结火车车厢的螺栓。如果螺栓没拴紧，或根本不存在，你的火车就跑不动了。

#+END_QUOTE

** 什么是第一扇门，如何判断
:PROPERTIES:
:NOTER_PAGE: (7 5041 . 5085)
:END:

``我的主角现在还能忽略情节，继续如先前一般过活吗？如果可以，那你的主角就还没穿过第一扇门。''

在阳神之中，当元妃把他抓走，请他教导狐妖的时候，洪易得知世界上还有武道这么一条路，此时他还有退路，可以回到以前的生活状态，他还可以回到侯府继续读书考试
