#+title: 佛教哲学 从西方哲学的角度看
* 佛教的概说
** 那些能够让某学说成为佛学的承诺
+ 苦、dukkha、不满足无处不在。苦可以暂时理解为对于生活的不满足。
+ 苦源自于“无明”，解决方法是本体论的彻底转向，以及对存在本质的觉悟（bodhi，菩提）
+ 一切现象都是“无常”、缘起、无自性的。即要将所有现象都看作终要灭亡、相互依存、没有独立本质的。
+ 根本的无明是将现象，尤其是自我，看作永恒存在的、独立的，并且认为有本质或自性。
+ 通过将现象视作无常、相互依存、无自性，可以消除或显著减少痛苦。（涅槃）
+ 合乎伦理的取向应该是培养：随喜、慈、悲，即致力于促进一切众生福祉。
  - 随喜(Mudita): 对他人的成就和幸福感到由衷的高兴（克服嫉妒）。
  - 慈（Metta）：愿众生快乐
  - 悲(Karuna):愿众生脱离痛苦
** 苦的普遍性，为什么 dukkha 的含义如此广泛。
在转法轮经中，佛陀说一切都是苦，这意味着世界上的一切东西，有情或无情，要么是苦的，要么是苦的原因。
苦苦，坏苦，行苦。分别是直接的痛苦、变化带来的痛苦、由条件带来的痛苦
*** 苦苦，直接感受到的痛苦
我们身上的痛苦。

即便是我们身上永远没有痛苦，但是世界上其他人身上也有这种痛苦，我们感到同情和悲伤，这种感情同样也是苦，我们意识到我们的东西仅仅是偶然的。

如果没有同情和愧疚，反而让我们陷入到另一种痛苦。我们不会认同一个对他人完全冷漠的自我形象，我们总有一个理想中的自己，这也是一种苦。
*** 坏苦，无常带来的痛苦
#+begin_quote
生年不满百，常怀千岁忧。昼长苦夜短，何不秉烛游？
#+end_quote

没有人能永远活着，我们都在衰老，而且知道这一点。生命的每一刻都在逼近疾病、衰弱、失去亲人以及死亡。

一切带来快乐的事物也是无常的，并在不断流逝：再好的美酒终会喝完，日落只持续几分钟，孩子会长大，我们也会厌倦曾经最爱的音乐。这些变化本身就是苦的来源。
*** 行苦，作为本体论的苦，存在的结构无处不在

佛教哲学的核心在于将世界指认为缘起的，即互相依存，这些缘、条件，大多不在我们的掌控之内。意识到这一点，没有人能自在的确保自己远离不幸，于是世界的结构本身与苦密不可分。
** 根本无明，不只是不了解，而是将现实中完全不存在的性质强加给事物

这不是一种推论，而是一种直觉。就像我们看到两条一样的线，但是因为箭头的缘故说他们一长一短。根本无明也是如此，我们有一种认识上的本能，将现实看作永恒独立并且具有内在本质的。

一个重要表现，就是我们用主客观二分的方式看待世界，也就是所谓的本质主义、柏拉图主义。

我们将世界看作客体，相对自己存在，世界是被认识的，客体是被认识的，自我是直接意识。这种立场在严肃的哲学观中是荒谬的。佛教哲学这样说：世界上的所有人都是这样看问题，而宇宙本身也不可能存在主观与客观的区分。

将我看作特殊的主体，而将世界上的事都看做与我和非我。——双重我执。

苦的来源是，本不该如此，全能错觉。我无法完全掌控人生是事实，但只有当我认为“我本该能完全掌控”时，这才成为苦。
** 认识论转向，觉悟，菩提，将世界看作其本来的样子。

通过对现实本性的觉醒，实现对苦的吹熄是可能的。这种认识论转向伴随着伦理学的取向：随喜慈悲。

苦源于对现实的误知——即我们将恒常性、独立性和内在本质错误地投射到本不具备这些性质的事物之上。因此，苦的缓解只能通过终止这种错误投射来实现。这里强调的是一种“止息”，尤其是其彻底形式——涅槃（nirvāṇa / nibbāna）。

涅槃这个词是一个比喻，对火的比喻。这涉及到五蕴（Pañca-skandha）。

蕴的原义是堆，不精确的堆，“skandha”的原始含义是火葬堆中的柴堆。因此，五蕴被理解为正在燃烧并被消耗的存在。

生命是一种燃烧状态，被苦燃烧，被不可控的力量消耗。而“涅槃”的本义是火焰的熄灭——就像吹灭一盏灯。

五蕴是色受想行识。物质、感受、思想知觉与辨别、心理倾向和习性、意识。

更重要的是，苦很大程度上并不是后天的。有的是理论性的，即后天的，由错误哲学产生，是对日常经验中这种倾向的系统化与辩护。第二种是先天的、本能的，需要一种彻底的转向。

于是，主客对立消失、我不再被视作特殊。我们不再只关心“我的快乐”，而是对“快乐本身”感到喜悦，对“痛苦本身”产生回应，致力于促进任何人的福祉
* 缘起、无常，佛教形而上学

缘起、无常、无自性；二禘。
** 缘起。佛教哲学的全部
此有故彼有，此生故彼生。此无故彼无，此灭故彼灭。
