#+title: 小说修辞学
#+startup: content

* 讲述和显示
+ 作者要反驳一个流行观点：好的小说要显示而不能讲述。
+ 作者会用文学史上的例子来证明，讲述一直存在且有效。
+ 作者的声音永远无法消除，问题不在于是否“讲述”，而在于如何“讲述”


通过浏览，我们要提出的问题是：
1. 什么是讲述，什么显示，这两个概念的区别是什么。讲述在这里地指作者告诉读者应当怎样看待人物，而显示则让读者自行推断，。区别在于作者与其代言人是否介入
2. 为什么批评家认为显示比讲述更高级，这个转变是怎么发生的。从福楼拜开始，这一转变涉及各种复杂问题，被归纳为艺术的显示和非艺术的讲述的区别。
3. 布斯为何认为这种二分法是“武断的”？
   这无法解释一个问题：为什么优秀作家的讲述比坏作家的显示更能打动人们。
4. 作者为什么用《约伯记》和荷马史诗作为例子？它们如何证明“讲述”的价值？
   约伯记的作者直接告诉我们约伯是正义的，没有罪，没有受到上帝厌弃。
   荷马直接告诉读者应当怎样看待人物，某件事情发生的原因是什么。我们应该用怎么样的眼光来看人物和事件。

   这两者，特别是占重点的荷马，是毫无疑问是文学的。约伯记和荷马史诗并没有用来证明讲述的价值，这部分是十日谈证明的。

5. 为什么讲述不能完全消失。
   为了某些原因，如篇幅，作者直接告诉读者关于人物的性格、事迹会产生巨大的修辞效果。
   作者的不同声音是存在的，它不能完全消失。
6. 《十日谈》的两个故事，作者想说明什么？

   作者想说明，讲述在特定情况下也能产生巨大的效果，比如，由于篇幅，作者不能去显示蒙德里哥的种种特质和蒙娜的优秀，只能告诉读者，把重点放在更具戏剧性的场面上来。
   要描写蒙娜值得被爱，配得上爱，并且兼顾篇幅，作者就只能直接告诉读者她的性格，并且（显示）让读者进入她的心中，看到她的贞洁和高尚，但是，最终屈服于更加合理的感情——对儿子的爱。

   同样的构思发生在男主人公身上，作者直接讲述他的性格，然后佐以展示内心活动来证实，这样一来，他的行为和话语完全是内心的对应，不至于让读者理解成滑稽。

   于是，蒙娜就可以选择这位高尚的先生了。

   这里分析反驳了那种认为“客观”或“戏剧式”叙述天然优于作者直接介入的观点。   作者的主要手段是归谬法，如果不这样做，那么达到相同的艺术效果就会花更多的篇幅，到的头重脚轻，不见重点。

7. 作者最终如何看待“讲述”与“显示”的关系？
   讲述与显示需要合理的搭配，达到相应的艺术效果，就像在十日谈里那样。
8. 作者的多种声音是哪些声音
   + 直接致辞，所以以作者本人身份做的评论

   + 介入性更少的议论

   + 进入人物的内心，转换角度

   + 所有的内心观察？

   + 所有混合了作者观点的评价：比喻、典故……

   + 事件的安排顺序也混合了作者的声音

   + 讲述什么故事也混合了作者的声音

   + 讲述，即作者的声音、作者的介入，发生在了讲述什么故事、讲述谁的故事这些决定中。显示的每一件事情，都是为了讲述服务。
9. “客观的”或“非人格化”叙述被许多作家和批评家奉为圭臬。根据你的理解，支持这种观点的主要理由可能是什么？布斯对此提出了哪些质疑？他认为单纯追求“显示”或“非人格化”会带来什么问题？
   主要理由可能是，如果作者直接讲述自己关于某些事情的观点，会破坏沉浸感、代入感。

   提出的质疑：作者的声音永远不可能消失，单纯追求显示会导致讲述的不可能，因为显示都是为了讲述服务
10. 如果小说家试图彻底清除作者的声音，这一行为本身是否也是一种具有特定意图的“讲述”？
    如果严格来讲，是的。



我有一点认为布斯刻意误解了所谓的讲述——讲述本身也是一个含糊不清的术语，如果将讲述看作者的声音的话，小说家的意思可能是，那种破坏沉浸感的，让叙述者主动出现发表观点，而不是忠实记录的。核心在于是否让读者意识到小说本身的存在。包括：
+ 反对作者直接出场说教
+ 主张通过场景、对话、行动来呈现（如海明威的冰山理论）
+ 追求一种“客观性”幻觉，让读者忘记文本是建构的


摘要。
讲述与显示的对比，约伯记、荷马史诗作者发表对角色的看法，引导读者，与现代小说作者的退场的比较。引出问题，这种二分会引发更艰难的问题。

用十日谈中的例子举例，讲述是不可或缺的。为了篇幅、喜剧效果，作者不能去展开另外的 pov，或者用事迹显示主人公的事迹；为了方便的引导读者的看法，也在篇幅允许之内进行讲述。

通过不断去除各种“作者的声音”，如直接议论、较少的议论、如何安排事件与选择材料、为什么选择特定的事件与 pov，对是作者的声音。由此证明了作者的声音可能完全退场。
* 普遍规律之一：真正的小说一定是现实主义的

小标题：
+ 正当的反叛到残缺的教条
+ 不同的种类到普遍的性质
+ 早期的普遍标准
+ 普遍标准的三个根源
+ 现实主义幻觉的强度
+ 作为直接幻觉的小说
+ 论现实主义之间的区别
+ 强度的安排


主题：显示和讲述。从活生生的到公式化的僵死。

重点在于。选择把什么加以完全戏剧化，让什么隐藏于幕后，什么需概括，什么要提高。像任何艺术一样，这一艺术是不能从抽象规律中学习到的。


问题：
1. 早期讲述和显示的区分的人的观点是什么，这些观点怎么变得僵硬了
2. 这期间的过程是什么，有那些代表的言论
3. 这一区分为什么被广泛接受
4. 人为什么寻找普遍标准
5. 早期有哪些普遍标准，举了那些例子
6. 普遍标准的三个起源是哪些
7. 逼真——现实主义的幻觉的需求有哪些弱点？忽略了什么
8. 小说应该真实，除了排除作者评论之外，还有什么表现。
9. 为什么这种技巧的自然不可能，有哪些表现。
* review
讲述和显示不是对立的。

将它们对立起来，从而划分出艺术的显示和非艺术的讲述是武断的。一则，讲述有必要的艺术效果可以实现；二则，作者的声音不可能完全去除。
